###
POST http://localhost:8080/pessoas HTTP/1.1
content-type: application/json

{
    "apelido": "fdsfsafa",
    "nome": "William",
    "nascimento": "1987-11-12",
    "stack": ["java", "cobol"]
}

###
GET http://localhost:8080/pessoas/d51300ca-05de-44d0-b062-194b0715e340 HTTP/1.1
Accept: application/json

###
GET http://localhost:8080/pessoas?t=java HTTP/1.1
Accept: application/json

###
GET http://localhost:8080/contagem-pessoas HTTP/1.1
Accept: text/plain

###
POST http://localhost:9999/pessoas HTTP/1.1
content-type: application/json

{
    "apelido": "hkh",
    "nome": "William",
    "nascimento": "1987-11-12",
    "stack": ["java", "cobol"]
}

###
GET http://localhost:9999/pessoas/d35c2093-9632-485a-9a4b-272ed2c3e73e HTTP/1.1
Accept: application/json


###
GET http://localhost:9999/pessoas?t=cobol HTTP/1.1
Accept: application/json